## Machine Learning With Python: Linear Regression Multiple Variables


### Sample problem of predicting home price in monroe, new jersey (USA)


##### Below is the table containing home prices in monroe twp, NJ. Here price depends on area (square feet), bed rooms and age of the home (in years). Given these prices we have to predict prices of new homes based on area, bed rooms and age.

![](data/homeprices.jpg)

###### Given these home prices find out price of a home that has,

**3000 sqr ft area, 3 bedrooms, 40 year old**

**2500 sqr ft area, 4 bedrooms, 5 year old**


##### We will use regression with multiple variables here. Price can be calculated using following equation,



![](data/equation.jpg)

##### Here area, bedrooms, age are called independant variables or **features** whereas price is a dependant variable



In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

C:\Users\P\anaconda3\lib\site-packages\scipy\__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.4)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "


In [2]:
df = pd.read_csv('data/homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   area      6 non-null      int64  
 1   bedrooms  5 non-null      float64
 2   age       6 non-null      int64  
 3   price     6 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 320.0 bytes


In [5]:
df.describe()

area  bedrooms        age          price
count     6.000000   5.00000   6.000000       6.000000
mean   3416.666667   4.20000  16.500000  648333.333333
std     587.934237   1.30384   8.288546  109117.673484
min    2600.000000   3.00000   8.000000  550000.000000
25%    3050.000000   3.00000   9.750000  572500.000000
50%    3400.000000   4.00000  16.500000  602500.000000
75%    3900.000000   5.00000  19.500000  722500.000000
max    4100.000000   6.00000  30.000000  810000.000000

In [6]:
df.columns

Index(['area', 'bedrooms', 'age', 'price'], dtype='object')

In [7]:
df['bedrooms'].unique()

array([ 3.,  4., nan,  5.,  6.])

##### Data Preprocessing: Fill NA values with median value of a column

In [9]:
df['bedrooms'].median()

4.0

In [9]:
df['age']

0    20
1    15
2    18
3    30
4     8
5     8
Name: age, dtype: int64

In [13]:
df['bedrooms'] = df['bedrooms'].fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   area      6 non-null      int64  
 1   bedrooms  6 non-null      float64
 2   age       6 non-null      int64  
 3   price     6 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 320.0 bytes


In [14]:
X = df.drop(columns=['price'])
X

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [15]:
y = df['price']
y

0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: price, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [17]:
x_train

area  bedrooms  age
1  3000       4.0   15
3  3600       3.0   30
0  2600       3.0   20
4  4000       5.0    8

In [18]:
x_test

area  bedrooms  age
5  4100       6.0    8
2  3200       4.0   18

In [19]:
y_train

1    565000
3    595000
0    550000
4    760000
Name: price, dtype: int64

In [20]:
y_test

5    810000
2    610000
Name: price, dtype: int64

In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
model = LinearRegression()

In [23]:
model.fit(x_train,y_train)

LinearRegression()

In [25]:
y_pred = model.predict(x_test)
y_pred

array([608500., 554875.])

In [26]:
pd.DataFrame({'y_test':y_test,'y_predict':y_pred})

y_test  y_predict
5  810000   608500.0
2  610000   554875.0

In [32]:
#3000 sqr ft area, 3 bedrooms, 40 year old
# 2500 sqr ft area, 4 bedrooms, 5 year old

In [31]:
print(model.predict([[3000,3,40]]))
print(model.predict([[2500,4,5]]))

[262000.]
[638125.]


In [34]:
model.coef_

array([    236.25, -175125.  ,  -19125.  ])

In [35]:
model.intercept_

843624.9999999998

In [36]:
# Y = m1 * X1 + m2 * X2 + m3 * X3 + b (m1,m2,m3 is coefficient and b is intercept)

112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540384


498408.25157402386

In [37]:
from sklearn.metrics import mean_squared_error, r2_score

In [45]:
print("MSE:",mean_squared_error(y_test,y_pred))
print("R2 Score: ",r2_score(y_test,y_pred))
print("RMSE:",np.sqrt(mean_squared_error(y_test,y_pred)))

MSE: 21820507812.499813
R2 Score:  -1.1820507812499814
RMSE: 147717.66249335188
