In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('data/titanic.csv')

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
# pip install pandas-profiling --user
# pip install ydata-profiling --user

In [5]:
from ydata_profiling import ProfileReport

In [6]:
prof= ProfileReport(df)
prof.to_file(output_file='output.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [7]:
df.shape

(891, 12)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [9]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [10]:
df['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [11]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [12]:
df['Age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [13]:
df['Age'] = df['Age'].fillna(df.Age.median())

In [14]:
df['Age'].unique()

array([22.  , 38.  , 26.  , 35.  , 28.  , 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  ,  8.  ,
       19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  , 49.  ,
       29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  , 16.  ,
       25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  , 71.  ,
       37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 , 51.  ,
       55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  , 45.5 ,
       20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  , 60.  ,
       10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  , 70.  ,
       24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [15]:
df.Embarked.unique()[2]

'Q'

In [16]:
df['Embarked'] = df['Embarked'].fillna(df.Embarked.mode()[0])

In [17]:
df.Embarked.unique()

array(['S', 'C', 'Q'], dtype=object)

In [18]:
df.Cabin.unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [19]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [20]:
df['Cabin'] = df['Cabin'].fillna(df.Cabin.mode()[0])

In [21]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object 
 11  Embarked     891 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [23]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [30]:
X =df.drop(columns=['PassengerId', 'Survived','Name','Fare','Ticket','Cabin']) 
y=df['Survived']

In [31]:
X

Pclass     Sex   Age  SibSp  Parch Embarked
0         3    male  22.0      1      0        S
1         1  female  38.0      1      0        C
2         3  female  26.0      0      0        S
3         1  female  35.0      1      0        S
4         3    male  35.0      0      0        S
..      ...     ...   ...    ...    ...      ...
886       2    male  27.0      0      0        S
887       1  female  19.0      0      0        S
888       3  female  28.0      1      2        S
889       1    male  26.0      0      0        C
890       3    male  32.0      0      0        Q

[891 rows x 6 columns]

In [32]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [33]:
# Encoding (ordinal encoding , label encoding, onehot encoding)
# from sklearn.preprocessing import OrdinalEncoder
# Get dummies from pandas Library
pd.get_dummies(X,columns=['Sex','Pclass'],dtype=int)

Age  SibSp  Parch Embarked  Sex_female  Sex_male  Pclass_1  Pclass_2  \
0    22.0      1      0        S           0         1         0         0   
1    38.0      1      0        C           1         0         1         0   
2    26.0      0      0        S           1         0         0         0   
3    35.0      1      0        S           1         0         1         0   
4    35.0      0      0        S           0         1         0         0   
..    ...    ...    ...      ...         ...       ...       ...       ...   
886  27.0      0      0        S           0         1         0         1   
887  19.0      0      0        S           1         0         1         0   
888  28.0      1      2        S           1         0         0         0   
889  26.0      0      0        C           0         1         1         0   
890  32.0      0      0        Q           0         1         0         0   

     Pclass_3  
0           1  
1           0  
2           1  
3           0  
4           1  
..        ...  
886         0  
887         0  
888         1  
889         0  
890         1  

[891 rows x 9 columns]

In [34]:
# drop first
X=pd.get_dummies(X,columns=['Sex','Pclass','Embarked'],drop_first=True,dtype=int)

In [35]:
X

Age  SibSp  Parch  Sex_male  Pclass_2  Pclass_3  Embarked_Q  Embarked_S
0    22.0      1      0         1         0         1           0           1
1    38.0      1      0         0         0         0           0           0
2    26.0      0      0         0         0         1           0           1
3    35.0      1      0         0         0         0           0           1
4    35.0      0      0         1         0         1           0           1
..    ...    ...    ...       ...       ...       ...         ...         ...
886  27.0      0      0         1         1         0           0           1
887  19.0      0      0         0         0         0           0           1
888  28.0      1      2         0         0         1           0           1
889  26.0      0      0         1         0         0           0           0
890  32.0      0      0         1         0         1           1           0

[891 rows x 8 columns]

In [36]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Age         891 non-null    float64
 1   SibSp       891 non-null    int64  
 2   Parch       891 non-null    int64  
 3   Sex_male    891 non-null    int32  
 4   Pclass_2    891 non-null    int32  
 5   Pclass_3    891 non-null    int32  
 6   Embarked_Q  891 non-null    int32  
 7   Embarked_S  891 non-null    int32  
dtypes: float64(1), int32(5), int64(2)
memory usage: 38.4 KB


In [39]:
#pip install --upgrade scikit-learn
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [41]:
X_train

Age  SibSp  Parch  Sex_male  Pclass_2  Pclass_3  Embarked_Q  Embarked_S
30   40.0      0      0         1         0         0           0           0
10    4.0      1      1         0         0         1           0           1
873  47.0      0      0         1         0         1           0           1
182   9.0      4      2         1         0         1           0           1
876  20.0      0      0         1         0         1           0           1
..    ...    ...    ...       ...       ...       ...         ...         ...
534  30.0      0      0         0         0         1           0           1
584  28.0      0      0         1         0         1           0           0
493  71.0      0      0         1         0         0           0           0
527  28.0      0      0         1         0         0           0           1
168  28.0      0      0         1         0         0           0           1

[712 rows x 8 columns]

In [42]:
y_test

707    1
37     0
615    1
169    0
68     1
      ..
89     0
80     0
846    0
870    0
251    0
Name: Survived, Length: 179, dtype: int64

In [43]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)

In [44]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [47]:
y_pred=knn.predict(X_test)

C:\Users\P\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:211: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [48]:
pd.DataFrame({'Ytest':y_test,'Ypred':y_pred})

Ytest  Ypred
707      1      0
37       0      0
615      1      1
169      0      0
68       1      0
..     ...    ...
89       0      0
80       0      0
846      0      0
870      0      0
251      0      0

[179 rows x 2 columns]

In [50]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7206703910614525